export const preRegisteredGames = {
  assassinsCreedOdyssey: [
    {
      title: 'Isso. É. Esparta!',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Brilhante!',
      description: 'Adquira e equipe seu primeiro item Lendário.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Uma Odisseia em Progresso',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Eu Sou a Lenda',
      description:
        'Equipe 1 arma corpo a corpo Lendária e 5 partes de armadura Lendárias.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Credo Fashionista',
      description: 'Equipe um conjunto de Armadura Lendária.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Erros Passados',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Melhor, Mais Rápido, Mais Forte',
      description: 'Melhore o Adrasteia pela primeira vez.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Velocidade Máxima',
      description: 'Parta um navio ao meio.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Deixe Sua Marca',
      description: 'Faça seu primeiro entalhe.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Você Trabalha para Mim Agora',
      description:
        'Recrute e designe um NPC (personagem não-jogável) Lendário para o seu barco.',
      isItLost: false,
      isDone: false,
    },

    {
      title: 'Mal Descoberto',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Nos Braços de Afrodite',
      description: 'Passe a noite com outro personagem.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Flagelo do Egeu',
      description: 'Afunde o primeiro Navio Épico.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Herói Sob Contrato',
      description:
        'Vença sua primeira conquista em terra em qualquer região, exceto Megaris, na Jornada Heroica.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Mentes Brilhantes',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Mestre da Guerra',
      description:
        'Mate o Líder de qualquer região com poucos recursos além de Megaris.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Das Cinzas',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'A Queda da Democracia',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Toque de Midas',
      description: 'Entalhe um Efeito Lendário em um Item Lendário.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Infame',
      description: 'Eleve a Recompensa por você até o nível máximo.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Uma Cabeça a Menos…',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Poder dos Deuses',
      description: 'Adquira uma Habilidade ativa de Nível 3.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Legado',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Em Busca do Ouro',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Os Argonautas',
      description: 'Encha o Adrasteia de Tenentes Lendários.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Uma Lenda se Formando',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Esporte de Sangue',
      description: 'Derrote um Mercenário na Arena.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Enigma da Esfinge',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Retomando Atenas',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Fim da Odisseia',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Labi(rindo) do Minotauro',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Semideus',
      description: 'Chegue ao Nível 50.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'De Olho na Recompensa',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Cajado do Relâmpago',
      description: 'Derrote Estéropes, O Portador do Relâmpago.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'A Ira das Amazonas',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Não se Divertiram?',
      description: 'Torne-se o Campeão da Arena.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Topo da Cadeia Alimentar',
      description: 'Torne-se o Mercenário número um.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'À Imagem de Perseu',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'O Culto Desmascarado',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Legado Restaurado',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Mestre da Caça',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Sem deixar vestígio',
      description: 'Mate 10 inimigos com a habilidade Véu da Morte.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Protetor Solar Vulcânico',
      description: 'Derrote Arges, O Iluminado.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Senhor dos Mares',
      description: 'Alcance o nível de melhoria Lendário com o Adrasteia.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'A Herdeira das Memórias',
      description: 'Conclua A Herdeira das Memórias.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Misthios Em Treinamento',
      description:
        'Conclua 20 Recompensas, Contratos de Guerra ou Missões Navais dos Quadros de Mensagens.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Eu Tenho a Força',
      description: 'Realize um Ataque de Avassalamento com cada tipo de arma.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Filhas de Lalaia',
      description: 'Complete Filhas de Lalaia.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Intervenção Divina',
      description: 'Complete Intervenção Divina.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Um Amigo Pelo Qual Vale a Pena Morrer',
      description: 'Conclua Um Amigo Pelo Qual Vale a Pena Morrer.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Irmandade do Coração Viajante',
      description: 'Conclua Irmandade do Coração Viajante.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'O Início de um Legado',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Visão Vermelha',
      description: 'Mate 10 inimigos com a habilidade Fúria da Linhagem.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'De Ilha em Ilha',
      description:
        'Conclua 20 missões nas ilhas de Pefka, Obsidiana e Abantis.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Toda História Tem um Final',
      description: 'Conclua Toda História Tem um Final.',
      isItLost: false,
      isDone: false,
    },
    {
      title: '"Todos saem ganhando!"',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Predador e Presa',
      description: 'Mate todos os Anciões da Ordem dos Caçadores na Macedônia.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Sangue de Leônidas',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'O Show Tem que Continuar',
      description: 'Complete O Show Tem que Continuar.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'A Imagem da Fé',
      description: 'Complete A Imagem da Fé.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Um Dia Muito, Muito Ruim',
      description: 'Conclua Um Dia Muito, Muito Ruim.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Concentrando Forças',
      description: 'Colete todas as Revelações dos Guardiões no Episódio 1.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Fogo na Água',
      description: 'Incendeie 10 navios inimigos.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Sem Mais Governantes',
      description: 'Mate todos os Supervisores no Elísio.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Na Face dos Deuses',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Começo Agridoce',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Legado de Um Poeta',
      description: 'Complete Legado de Um Poeta.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Abrindo o Céu',
      description: 'Mate todos os Anciões da Ordem da Tormenta em Acaia.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Cachorro mau!',
      description: 'Derrote Cérbero.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Confie em Mim, Eu Sou um Doutor',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Olhar de Desprezo',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Pelo Amor da Pérsia',
      description: 'Mate todos os Anciões da Ordem dos Domínios em Messara.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Minha Hora de Brilhar',
      description:
        'Use a habilidade A Chama do Inverno para matar 10 inimigos.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Encontre Meu Assassino',
      description: 'Encontre o Assassino do Monumento de sua Família.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Dois Lados da Mesma Moeda',
      description: 'Complete Dois Lados da Mesma Moeda.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Coração Das Trevas',
      description: 'Mate todos os Monstros no Submundo.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Ira de Ártemis',
      description: 'Derrube um navio enquanto usa uma Habilidade de predador.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Escuridão e Luz',
      description: 'Conclua Escuridão e Luz.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Complicações',
      description: 'Complete Complicações.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Hora de Acertar Contas',
      description: 'Complete Hora de Acertar Contas.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Fechando a Ferida',
      description: 'Complete Fechando a Ferida.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'O Destino de Atlântida',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Meu Ídolo',
      description: 'Adquira sua primeira estátua de bronze.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'A Vigia do Estígio',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Sem Correntes',
      description: 'Complete Sem Correntes.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Guardião das Terras Prósperas',
      description: 'Complete Guardião das Terras Prósperas.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Em Busca do Arco Dourado',
      description: 'Conclua Em Busca do Arco Dourado.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Cão de Guarda',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'O Primeiro',
      description: '',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Um Encontro com Ártemis',
      description: 'Conclua Um Encontro com Ártemis.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Lobo em Pele de Lobo',
      description: 'Mate Licaon, O Velho.',
      isItLost: false,
      isDone: false,
    },
    {
      title: 'Nem Uma Só Queda',
      description: '',
      isItLost: false,
      isDone: false,
    },
  ],
}
